github/training-kit

- _layouts/cheat-sheet.html
- _stylesheets/page.scss
- downloads/subversion-migration.md
Prepares final Markdown content and addresses adjustments mentioned [here](https://github.com/github/training-kit/issues/283#issuecomment-66727498).
**[Rendered](https://github.com/github/training-kit/blob/svn-cheat-sheet-1.0.0/downloads/subversion-migration.md)**
> SVN to Git Cheat Sheet 1.0.0 preparation

- _stylesheets/page.scss
- downloads/github-git-cheat-sheet.md
A first draft with minimally invasive markup in the markdown, and using common site-wide styles to mimic the [print-ready](https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf) layouts of the cheat sheet.
> Git cheat sheet web-layout mimicking print

- _javascript/curriculum.js
- _layouts/curriculum.html
Several undocumented but outstanding JS and layout issues are resolved in this PR:
> Bug fix for slide, slide-only modes

- intermediate/index.md
Following up with Intermediate curriculum similar to the summaries in https://github.com/github/training-kit/pull/292 for Foundations.
> Intermediate chapter summaries

- _stylesheets/curriculum.scss
Matches checkboxes of class slide objectives with visual design of site.
> Slide objective list styling

- advanced/index.md
The `--signoff` (or `-s`) option and the `--gpg-sign` (also `-S`) are not interchangeable. We have the right short-cut (`-S`) but this slide has the wrong long option. I think it's confusing, anyway.
`--signoff` (or `-s`) does this:
```
commit c41aebe7363901aa08e8d48879063432e8617c6a
Author: Joshua Wehner <joshua.wehner@github.com>
Date:   Fri Jan 16 17:10:08 2015 -0600
testing
Signed-off-by: Joshua Wehner <joshua.wehner@github.com>
```
`--gpg-sign` (or `-S`) does this:
```
commit 78c00b1441e0b1d03ef3271eb1cf6bdec05cb5ff
gpg: Signature made Fri Jan 16 17:11:08 2015 CST using RSA key ID A20F7983
gpg: Good signature from "Joshua Wehner <joshua.wehner@github.com>"
Author: Joshua Wehner <joshua.wehner@github.com>
Date:   Fri Jan 16 17:11:08 2015 -0600
testing
```
It might be worth re-visiting …
> --signoff -> --gpg-sign

- downloads/subversion-migration.md
This should fix the broken css on the training-kit for https://training.github.com/kit/downloads/subversion-migration.html
cc @jordanmccullough
> add leading path of subversion-migration

- _layouts/site.html
- downloads/subversion-migration.md
in #312 i accidentally misread what was needing to be sent to the `site` layout. This should fix it.
of course, the layout was also including an extra slash in the path for the stylesheet, but not in any of the javascript. whoops!
> send slash in leadpath on files, not in stylesheet

- intermediate/index.md
as our first time working through some commands,
we can't just set the options without a flag. If
we were already in a repository, this would work
but we wont get to that until further into the
class.
cc @jordanmccullough for review.
This addresses #307
> all config settings need to start global

- _config.yml
- _includes/top.html
- _layouts/course.html
This Pull Request fixes an issue that #318 introduced where links to courses and modules break when `training-kit` is served at https://training.github.com.
These changes add a `baseurl:` of `/kit` to the configuration file that Jekyll uses when generating links to courses and modules.
> Add better support for paths

- _layouts/module.html
This Pull Request adds the `site.baseurl` variable to image slides for better support when serving `training-kit` on https://training.github.com.
> Add baseurl to image slides

- _javascript/curriculum.js
- _layouts/course.html
- _layouts/module.html
- _stylesheets/curriculum.scss
This Pull Request updates the styling of the training kit with a few tweaks:
> Fix formatting

- _stylesheets/curriculum.scss
cc @loranallensmith, this makes it so when scrolling the TOC doesn't hide partially. (call this an OCD fix)
> make a bit more padding for toc so when scrolling it looks okay

- _javascript/curriculum.js
This Pull Request fixes a bug that was introduced in #322 where the table of contents disappeared when viewing the slides for Foundations, Intermediate, and Advanced classes.
The slides for these classes should now display the TOC while the slides for the new classes only contain links to courses.
> Support TOC in legacy classes

- downloads/pt/github-git-cheat-sheet.md
- index.html
I did a few interactive rebases to attempt to group the changes, so that if some of them are not accepted, the commits can be easily removed. How do you usually work? Should these all be squashed into one final commit?
In this PR, I am trying to translate things back to English to explain the changes to everyone. Let me now if I should clarify more.
The previous title did not sound right. The one I propose sounds like `GitHub's Git Cheat Sheet`.
I do not know where those were taken from, but it is very confusing to use `Marker` for `Remote`.
These changes were taken from Pro Git's translation, which IMO sound much better:
- I found that `Select` was being used for `Stage`, but it sounds too vague and there is no direct translation for that. On [section …
> Improve the Git Cheat Sheet in Portuguese

- _stylesheets/page.scss
- index.html
Hate such a big commit, but because of div tags being spread out on the new formatting, i took the approach of just one single commit.
cc @github/training-teachers for some feedback. We'll also need to incorporate this into training-web afterwards.
> switch formatting for two column git translation

- _javascript/curriculum.js
- _layouts/module.html
I've run into this problem where the on-screen timer doesn't update the countdown in some circumstances. Usually this is just a mildly annoying/humorous glitch -- the countdown says that there's "39 minutes left" when we all know that's not quite right -- but it came up in both of my recent on-site classes and I wanted to investigate a bit.
The old timer works something like this:
```
duration = x
every second:
duration = duration - 1
display duration
```
The problem with this is if something interrupts the `every second` check, the duration doesn't shrink.
The new timer works more like this:
```
time to stop = x
every second:
duration = how long until time to stop
display duration
```
This way, even if (some/any) of the `every second` checks get interrupted (laptop is sleeping, etc.) the …
> Rework timer to work as expected when sleeping

- _modules/CONT-CLI-04_Two_Stage_Commit.md
- _modules/CONT-GHM-04_Two_Stage_Commit.md
I removed the word "either" in the list of file states. I believe either should be used when only two options are available.
> Removed usage of "either" in list of file states.

- _courses/github-for-everyone.md
[This line](https://github.com/github/training-kit/blame/master/_courses/github-for-everyone.md#L16) has been here since the initial import, but I can't make it make sense in my head and none of the videos I've reviewed actually show anyone doing this at all, let alone as the ~fifth thing in class.
I'm not sure what this is supposed to be, but my guess is that it should just go. :hocho: 
@github/training-teachers thoughts? objections? theories? explanations? concerns?
> Remove local repo from first segment in Everyone

- downloads/subversion-migration.md
@github/services-engineers tested this out lately, and the syntax for the command is `--stdlayout` instead of `--std-layout`
looking for a :+1: here!
> stdlayout instead of std-layout for svn migration

- index.html
This PR relabels the way Portuguese cheat sheets are presented so there's a separation between pt_BR and pt_PT. It also introduces the pt_PT to the kit landing page. Merging this myself since this is a pretty small change that should've really been introduced in #359
> add link to pt-pt cheatsheet

- README.md
The current URL is incorrect. It redirects to https://services.github.com/ because it's missing the trailing slash. Might as well put the final URL here. :smile: https://services.github.com/kit/
> Fix the training kit URL

- README.md
The old links gave a 404.
Now you get the index.md displayed, links to index-extras.md are still missing.
Fixes #358
> Fix links to point to the respective index.md

- advanced/index.md
This PR resolves #372. The need for the slide capture syntax was removed in https://github.com/github/training-kit/commit/933ce3a7b8a3b7aace864088d50bd184a982e290 but it snuck back in to this doc when I resolved a merge conflict. This PR changes it back to markdown only!
> Remove slide captures from advanced

- README.md
@github/services-training: hopefully this makes it a bit more clear about how to download this project. My goal was to call out this is a typical use case for people with firewall restrictions and hopefully the explanation of the release name is okay too.
cc @matthewmccullough (last person to edit the `script/makerelease` file), how would you feel about removing `script/makerelease`?
cc @azizshamim for ongoing offline packaging efforts.
> Readme cleanup offline package and build

- README.md
Just fixing a minor typo in the README.
> Fix typo in "GitHub for Everyone" link

- downloads/subversion-migration.md
This PR includes a fix for the broken link to the GitHub Importer as identified in issue #385.
Because the proposed URL fix (import.github.com) only redirects successfully for logged in users, this PR is **WIP**, pending further discussion.
Once the ideal link is determined, I can go ahead and update this PR.
> Fix broken link to GitHub Importer in SVN Migration cheat sheet

- _config.yml
- _includes/footer.html
- _includes/top.html
- index.html
The navigation on some cheat sheets that are generated in HTML is outdated. The changes introduced here should update the navigation to more closely resemble the nav used by the training team.
> Update nav on the HTML cheat sheets

- downloads/kr/github-git-cheat-sheet.md
- index.html
Thanks to @bitoiu for noticing that the KR and DE cheatsheets weren't linked. This PR adds links to them to the training-kit.
> Add Korean and German cheatsheets

- downloads/subversion-migration.md
> Fix the markdown header in subversion migration section.

- advanced/index-extras.md
There's a capture tag in the training slides that is stopping the build of training-kit. This PR should take care of it.
> Close capture tag in training slides

- _includes/timeline.html
@github/services-training this PR updates the title on the upcoming command line course to make it clear we are learning command line Git, not Hub. Will :ship: with 1 :+1:
P.S. this closes https://github.com/github/services-web/issues/630
> Update the Title on the CLI course

- community.md
Creating this PR to center the avatar images and handle text within the table found on the Community [page](https://services.github.com/on-demand/community/). This isn't a major change, I just liked the look of the centered images/text over the left-aligned content.
> Center avatars and handles on the Community page

- self-study.md
I originally named this file 'self-study' but based on a recommendation by @crichID I think it should be set to 'learning-path', so I need to fix that. 
I am making this PR as an opportunity to provide a list of guides and learning opportunities for newcomers to Git and GitHub. Times are based on me reading the different articles at a decent pace, so they aren't 100% accurate, but probably not off by too much.
Let me know what you think. @github/services-training  
It is currently accessed locally by adding this to the server address: `on-demand/self-study/`
> Create learning path file

- downloads/ar/github-git-cheat-sheet.md
- downloads/cn/github-git-cheat-sheet.md
- downloads/de/github-git-cheat-sheet.md
- downloads/es_ES/github-git-cheat-sheet.md
- downloads/fr/github-git-cheat-sheet.md
- downloads/github-git-cheat-sheet.md
- downloads/it/github-git-cheat-sheet.md
- downloads/ja/github-git-cheat-sheet.md
- downloads/kr/github-git-cheat-sheet.md
- downloads/pt_BR/github-git-cheat-sheet.md
- downloads/pt_PT/github-git-cheat-sheet.md
- downloads/sk/github-git-cheat-sheet.md
Per an email report, the cheat sheets currently show the use of `--other` instead of `--others` as an option for the ls-files command. The [online documentation shows that `--others` is the correct option](https://git-scm.com/docs/git-ls-files). This fixes the .md files, but leaves the PDFs untouched for now. This will also need to be fixed in #403.
Will :ship: with one approved review!
/cc @github/services-training FYI
> Change --other to --others in ls-files

- us-holidays.md
The on-demand site lists the dates when GitHub's trainers will not be available to offer assistance via Gitter. This PR updates the list to reflect the actual dates for 2017.
I also added a heading so people would know which year was reflected in the chart!
@github/services-training will merge with 1 :+1:
> Update with 2017 holidays

- README.md
⚠️  **Work in Progress** ⚠️ 
This pull request is a follow up to #415 and will strive to create a friendly README.
If you are reading this, what's missing? How can we make the process of customizing, building, and contributing to these materials less intimidating?
@github/services-training
> Newer, Friendlier README

- downloads/es_ES/github-git-cheat-sheet.md
- downloads/fr/github-git-cheat-sheet.md
- downloads/github-git-cheat-sheet.md
- downloads/ja/github-git-cheat-sheet.md
- downloads/pt_BR/github-git-cheat-sheet.md
- downloads/pt_PT/github-git-cheat-sheet.md
This PR fixes a bug found in #427 with the rendering of the html cheat sheets. 
Will :ship: with 1 :+1:.
> Fix leading path in cheat sheets so html will render properly

- _data/navigation.yml
- _includes/timeline.html
This pull request removes the beta tags from the Desktop and the CLI course in both the nav head and the timeline.
This shouldn't be merged until the tests are merged into the class repository [from this PR](https://github.com/githubschool/on-demand-github-pages/pull/60). 
@github/services-training Does this look OK to you? Is there anything else we're waiting on to remove the beta tags?
> Remove beta tags from Desktop & CLI

- _includes/activity/github-desktop/12-add-class-repo.md
- _includes/activity/intro-to-github/01-join-intro-repo.md
**TL;DR**
This changes the instructions so users will be added by creating an issue rather than commenting on an existing issue. 
This will need to be merged at the same time as [this related pull request in another repository having to do with managing the webhook](https://github.com/githubteacher/practice-sinatra/pull/4).
This solves several problems: 
- Users have been creating issues instead of commenting by mistake
- Threads can only have 2500 comments, which we have maxed out
@github/services-training How does this look? Is this a direction we want to go?
> Change instructions so users will be added by creating an issue

- _includes/tell-me-why/trouble-pushforcewithlease.md
- paths/git-trouble/fc-commitsucks.md
**TL;DR**
Recommend the usage of `git push --force-with-lease` instead of  `git push --force` 
closes #452 
should be ready for review @crichID
> Replace usage of push force by force-with-lease

- paths/git-trouble/fc-commitbroke.md
- paths/git-trouble/fc-wrongbranch.md
Wrong ticks on line 44 "Enter: 'git status'." which results in showing `git status` not in code formatting. Should be grave accent ( `` )
> Change wrong ticks on line 44 to grave accent

- _layouts/simple-class.html
- _layouts/splash.html
**TL;DR**
Some jitter was introduced when #435 was merged in (reproducible in Chrome). This PR should 🙏 hopefully resolve it.
Since the ribbon is included in the masthead, this PR removes it from the layouts. Not only did this introduce double ribbons, but it also interfered with the sidebar CSS. 
Hoping for 👀 from @beardofedu as the forking ribbon is his 👶. But anyone else that would like to review is welcomed.
> Fix CSS jitter

- paths/intro-to-github/06-find-coordinates.md
The link to [manually search for coordinates](https://mynasadata.larc.nasa.gov/latitudelongitude-finder/) in the intro course is broken so I am replacing it with https://landsatlook.usgs.gov/viewer.html
@github/services-training can I get a quick :+1:?
> Update link to manually search for coordinates

- _includes/tell-me-why/trouble-reset-xref.md
- paths/git-trouble/fc-accidentcommit.md
- paths/git-trouble/fc-commitbroke.md
- paths/git-trouble/fc-commitsucks.md
- paths/git-trouble/fc-manycommits.md
- paths/git-trouble/fc-wrongbranch.md
**TL;DR**
This PR fixes some broken links after changing the navigation structure. 
This PR closes #499 
I will 🚢 with 1 👍. CC/ @github/services-training for testing. To test, go to `git-out-of-trouble` and click links in paragraphs that will redirect you to 'getting set up'. 
cc/ @mwiesen
> Replace 01 with git-set-up in URLs

- _includes/activity/gh-pages/02-create-profile.md
- _includes/activity/gh-pages/03-create-new-page.md
- _includes/activity/gh-pages/04-more-content.md
- _includes/help-build-fail.md
- _layouts/intro-to-github.html
- _layouts/simple-class.html
- community.md
- paths/intro-to-github/12-celebrate.md
**TL;DR**
This PR removes the Chat option from on-demand. 
The chat option was always an experiment to see how many users would drop in and request help. After having the option available for ~ 1 year, we have found that a very small number of students use it. Most of these students also requested help in a GitHub issue or pull request, making chat redundant. 
This PR removes the chat option and attempts to reinforce the :+1: behavior of asking questions and requesting help in issues and pull requests.
/FYI @github/services-training for updates to comms
> Remove chat option from on-demand

- paths/windows/01a-installing-git.md
- paths/windows/03e-sync.md
With the release of the new Electron based Desktop application, Git will no longer be installed with Desktop. It will now prompt the user to download and install Git from git-scm.com. As a result, this PR removes the Desktop reference on the installing git page.
Also, the `Sync` button has changed in Desktop. Rather than deal with the complexity here, I removed it from the VS section since it was also the only other reference to Desktop in the course.
> Remove desktop references from windows

- _includes/activity/github-CLI/05-make-commits.md
This error occurs on the the following [page](https://services.github.com/on-demand/github-cli/add-commits-git), Step 5, bullet 1.
This was brought to our attention during the Nashville Patchwork. Shoutout to @crichID
**TL;DR**
Directions to leave VI didn't include a reference to the `Esc` key, and now it does.
👀  @crichID @hectorsector @brianamarie 
Looking for 1 👍  to 🚢
> Clean up instructions for exiting VI

- _data/navigation.yml
- _includes/timeline.html
- paths/github-cli/01-github-CLI-introduction.md
- paths/github-desktop/01-class-introduction.md
**TL;DR**
As GitHub Pages is a frequently searched term, I've modified the course title to include GitHub Pages and the specific interface used to interact with Git and GitHub. 
- Do people think this change looks 👍 ?
I will ping once I have given the content a quick once over.
> Change courses to include GitHub Pages reference in title

- README.md
**TL;DR**
In the README.md, there was a link to the learning path that didn't make sense. 
This resolves #524 
@github/services-training and @joshmorel for 👀 and 👍
> Update redundant link to study path

- _data/navigation.yml
removing the 'converting apps' section from the navigation
> remove converting apps from nav

- paths/electron/packaging-apps/outline.md
This pull request brings the first draft of the 'packaging' course for electron into the `electron-course` branch. 
I'm not sure exactly how these sections map out to the questions we want to answer and the workflow we want to advise, but I'm hoping we can get more detailed as we go along. 
cc @github/services-training and @leefaus for review and edits
> start outline for packaging apps

- _data/navigation.yml
- paths/electron/distributing/01-share-apps.md
- paths/electron/distributing/02-native-app-discovery.md
- paths/electron/distributing/03-sharing-on-websites.md
- paths/electron/distributing/outline.md
**TL;DR**
This pull request is for the draft of the third course in the [Electron path](https://github.com/github/training-kit/projects/2), Sharing Apps.
- Does this course cover the right amount of breadth and depth? 
- Is the native app info accurate?
- Can GitHub Pages work for hosting apps? 
- Would GitHub releases work for hosting apps?
- If not GitHub pages, what type of website is needed?
- What other hosting is recommended?
- ✏️ @github/services-training to fill in content 
- 💻 @github/services-training to test the activity
- 👍 and 💭 from @lee-dohm if we are moving in the right direction 
Not yet ready for review.
> Electron draft: Sharing and Distributing apps

- resources/cheatsheets/index.html
This pull request changes the language labels on cheat sheets. Now, a French cheat sheet won't say "French", it will say "Français". This resolves https://github.com/github/training-kit/issues/544. 
- Do we want to change the order of the cheat sheets now? They were alphabetized before in English. Now, I don't know how we should do it. 
- How can we check these are correct? 
@github/services-entireteam @JasonEtco What do you think?
> Change labels for git cheat sheets to be in language that they are in

- _includes/scripts.html
- assets/css/main.scss
- paths/intro-to-github/00-welcome.md
- paths/intro-to-github/12-celebrate.md
- script/bootstrap
In #567, the contributor map was broken due to removal of some apparently important CSS 😊  This fixes that issue, and it also adds some new steps to `script/bootstrap` to ensure that Primer is installed.
It also removes broken JS (from the old Jekyll theme). A full JS audit/rewrite is coming soon:tm:
> Fix the map

- README.md
Not sure if I am missing something here, but the href links in the README file are broken. Fixed them in this PR.
> Correct {{site.baseurl}} to "on-demand" fixing broken links

- _config.yml
When I merged in #593, I inadvertently broke pages that had no translation. This PR fixes that.
Before:
After:
I should probably get at least 2 other 👍 from anyone at @github/services-training to make sure I'm not breaking anything else!
> Add default page language

- index.html
The merge conflict course has an immediate need for some content fixes, so removing it from the timeline so they can be addressed. 
Super zoomed out image. MC course no longer listed
> Remove merge-conflict course from timeline

- _data/navigation.yml
- index_es.html
- resources/learning-path/index_es.html
This PR translates the site title (_On Demand Training_ ➡️ _Aprende a tu ritmo_) and the title of _Learning Path_ ➡️ _Ruta de aprendizaje_. It closes #583.
I can 🚢 with one 👀 from @dpmex4527, @mberasategi, or any other Spanish speakers (maybe @bescalante?) willing to take a quick peek that can help rate my translation.
> Translate site and learning path title to Spanish

- paths/git-trouble/fc-scenarios.md
- paths/git-trouble/fc-welcome.md
@github/services-training these errors were accidentally introduced in #612 - just a quick fix to correct indentation and make yaml happy.
> Restore yaml indentation

- assets/js/mapsAPI.js
Closes issue #627, which raised the issue of a console error that's triggered by this file's attempt to fetch google maps data on pages without the requisite `#map` element. This is a simple fix that checks to see whether `#map` is present before proceeding with the `.getJSON` AJAX function. Only the `/intro-to-github/` page contains the map, so the console error appears on every other page.
> Don't try to fetch map data unless #map is present

- _layouts/cheat-sheet.html
- downloads/subversion-migration.md
This PR fixes an issue reported by @brntbeer wherein the cheat sheet page for SVN Migrations was showing only one column instead of two.
Closes #640
> Fix columns issues on Migration Cheat Sheet page

- downloads/id/github-git-cheat-sheet.md
As I was cleaning up the cheatsheets, I discovered that the [Baha Indonesia cheatsheet](https://github.github.com/training-kit/downloads/id/github-git-cheat-sheet/) had some conflict markers that were committed. I've removed them all by accepting incoming changes.
@adhikasp @wisn @chocochino I see that you've committed to this file in the past, would you mind giving this some 👀?
> Remove conflict markers in Bahasa Indonesia cheatsheet

- script/package
In the training-kit README, a workflow is presented to create a local copy of the files to be served by a web-server. The first step of that workflow is to run `script/package`, but that step fails ...
This PR fixes two errors in the sed command inside script/package [ see comment by bazzaar in issue #554 ]
I subsequently ran through the corrected workflow on my local version of training-kit, and the web-served files are built and packaged successfully, and then display correctly in Firefox browser using the simple python web server.
As the sed regex didn't match the text in the `_config.yml`, perhaps some change had been made to the `_config.yml` file previously, ... maybe the keywords are no longer as expected in that file? Just a thought ...
hope this helps
bazzaar
> Corrected the sed -i command in script/package shell script [#554]

- downloads/pl/github-git-cheat-sheet.md
- index.html
**TL;DR**
Added basic translation to Polish.
> Translate Git cheat sheet to Polish

- downloads/submodule-vs-subtree-cheat-sheet.md
**TL;DR**
Fixing a typo in the `subtree` cheatsheet
@github/services-delivery
> fixing typo in subtree cheatsheet

- Gemfile.lock
Reverts github/training-kit#715 which broke the build
> Revert "Bump rubyzip from 1.2.2 to 2.0.0"

- CONTRIBUTING.md
**TL;DR**
The instructions for building the site locally were outdated. I updated them.
I saw the README talks about `script/package` that doesn't exist anymore, but I didn't remove it as I couldn't figure the replacement procedure. I can update this branch with changes to the README if that's desired.
> CONTRIBUTING: update 'Building and testing' instructions

- downloads/id/github-git-cheat-sheet.md
- downloads/sk/github-git-cheat-sheet.md
- downloads/submodule-vs-subtree-cheat-sheet.md
**TL;DR**
The "Submodules vs. Subtrees" cheat sheet was missing some important information about working with projects that have submodules, mainly that `git pull` and `git checkout` do not, by default, update the working directory of the submodule(s), causing much confusion and sorrow.
I also improved the other sections of this cheat sheet to add details and use more modern Git commands and flags. Each commit message explain the changes in details.
The `submodule.recurse` config is super useful, but it works correctly for `git pull` only starting with Git 2.15. Should that be mentioned ?
> Improve and modernize the submodule cheat sheet

- script/package
**TL;DR**
This pull request brings back a deleted `script/package`. It was deleted during a refactor, but we believe customers still occasionally use this to generate the training-kit to be used within their firewalls.
This closes #728 
Community reviews welcome, in addition to @github/services-programs 👀
> Bring back script/package

- .github/workflows/jekyll.yml
Checks failing due to issue with docker image.  workaround is to specify jekyll version.
https://github.com/envygeeks/jekyll-docker/issues/272
> specify jekyll version to workaround docker image bug

- index.html
**TL;DR**
We are open sourcing the training manuals. This PR adds links to those manuals, so that the `training-kit` landing page is a resource for finding other learning content in addition to cheat sheets.
N/A
As we move the training manual for developers into the GitHub org, we will need to update the link here. 
cc @parkerbxyz @github/ps-programs for awareness and review 👀
> Add links to manuals

- git-guides/git-clone.md
- git-guides/git-overview.md
- git-guides/git-pull.md
- git-guides/git-push.md
- git-guides/git-status.md
Title. Default default branch name was changed to master [in October](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/). This PR just updates pages to account for the rename.
> Change all instances of "master" to "main"

- git-guides/git-clone.md
Changed `[banch-name]` to `[branch-name]` under Related Terms
> Typo in git-commit at git-branch description

- git-guides/git-commit.md
**TL;DR**
Fix command to save and exit Vi / Vim in line 29. Was `:w`, changed to `:wq`.
> Fix command to exit Vi / Vim in line 29

- _config.yml
This PR excludes `package.json` and `package-lock.json` from being deployed to production.
> Exclude package.json and package-lock.json from production

- _includes/footer.html
- _includes/header.html
- _includes/seo.html
- index.html
- Heading elements are in a sequentially-descending order (h3 was after h1)
- Links have a discernible name
- Document have a meta description
Lighthouse score is now much better
> Accessibility and SEO improvements

- downloads/zh_TW/github-git-cheat-sheet.md
- index.html
**TL;DR**
Add github-git-cheat-sheet.md in zh_TW and update index.html accordingly.
No Questions :)
Wait for reviewers' opinions to decide the next steps. 
Hi @parkerbxyz @brianamarie, I noticed that you were handling the recent pull requests, so I tagged you here hoping that you can help review this PR. Hope that it doesn't bother you.
> Add github-git-cheat-sheet in zh_TW
