github/training-kit

- _buildscripts/theme
- _includes/hydeslides/impressjs/slidedeck
- _includes/hydeslides/revealjs/head
- _includes/hydeslides/revealjs/scripts
- _includes/hydeslides/revealjs/slidedeck
- _includes/hydeslides/revealjs/slidedeck-diagrams
- _includes/hydeslides/revealjs/svg
- _includes/top.html
- _javascript/curriculum.js
- _javascript/page.js
- _layouts/slide.html
- _stylesheets/curriculum.scss
- _stylesheets/page.scss
- slides/README.md
- slides/_posts/api/0001-01-01-How-do-I-test-it.md
- slides/_posts/api/0001-01-02-What-URL-do-I-use.md
- slides/_posts/api/0001-01-03-What-can-it-do.md
- slides/_posts/api/0001-01-04-What-can-it-do.md
- slides/_posts/api/0001-01-05-What-can-it-do.md
- slides/_posts/pages/getting-started/0007-01-01-privacy.md
- slides/dependencies/themes/core/css/core-impressjs.css
- slides/dependencies/themes/core/css/core.css
- slides/dependencies/themes/github/css/impressjs.scss
- slides/dependencies/themes/github/css/overrides.scss
- slides/dependencies/themes/github/css/revealjs.css
See: https://github.com/github/training-kit/issues/297
> Convert all hard tabs to soft tabs (double space)

- advanced/index.md
- foundations/index-extras.md
- foundations/index-simple.md
- foundations/index.md
- intermediate/index-extras.md
- intermediate/index.md
- Fixes misspellings and a few errant words found in the Foundations, Intermediate, and Advanced content.
- Corrects inconsistent capitalization of GitHub terms.
> Fix typos.

- workbooks/es/github-foundations.md
Hi @matthewmccullough : I have taken care of a few minor issues that I had mentioned [here](https://github.com/github/training-kit/issues/308) a couple of days ago.  Please let me know if you have any questions.  Cheers!
> Miscellaneous fixes in the Spanish version of 'github-foundations.md'

- advanced/index.md
This includes no substantive content changes.
> Simplify phrasing and diction. Fix grammatical errors.

- downloads/cn/github-git-cheat-sheet.md
Noticed the leading path here was slightly off for loading stylesheets and the such. this should fix it. cc @sdq for your amazing work on this the last couple of days
> load proper stylesheet for cn translation

- _javascript/curriculum.js
- _layouts/course.html
- _layouts/module.html
- _stylesheets/curriculum.scss
- downloads/cn/github-git-cheat-sheet.md
- index.html
- workbooks/cn/github-intermediate.md
1. Add Chinese github intermediate workbook.
2. Revise Chinese git cheat sheet. Fix some translation problems.
> update Chinese version for the training kit

- _courses/github-for-developers.md
- _courses/github-for-everyone.md
Moving this PR over here from [training-web](https://github.com/github/training-web/pull/351). 
@brntbeer am I missing anything else?
> Trimming down course descriptions

- downloads/de/github-git-cheat-sheet.md
I translated the Cheat Sheet into German. Some words or sentences did not translate very well into German terms. E.g. "index" translates way easier (into "Index") than of "staging area" (into "Vorbereitungszone"?), so I used the terms that made it sound less awkward.
Maybe someone with better knowledge of "official" Git terminology in German want's to leave some comments? (e.g. authors of German Git-Books such as @esc, @Feh, @progit-de)
> German Cheat Sheet translation

- workbooks/github-intermediate.md
> Fix a typo

- _javascript/curriculum.js
Recommended to use .text() on the last line instead of .html(). Also, this not a security issue, but the regex does not recognized usernames with hyphens (-)
Recommended changes:
@github/training-teachers are you okay making the further edits of removing the "-" for the regex? 
cc: @mastahyeti
> Changed .html(data.name) to .text( ) in line 24

- downloads/github-git-advanced-cheat-sheet.md
Hey @brntbeer,
As discussed over #352, created a PR to get started with a more advanced version of cheat sheet.
Thanks,
Harshita
> Advance Cheat Sheet for Git and Github

- README.md
@crichID not sure how you feel about me mentioning that you or myself should be @mentioned for `.pdf` viewing, but it seemed like the best approach given https://github.com/github/training-kit/pull/359#issuecomment-215573822 and us not uploading the Adobe Illustrator file to this repo (and maybe the fact that later we'll have this done automatically?)
> updated instructions on where and what to contribute to

- downloads/kr/github-git-cheat-sheet.md
The cheat sheet has been translated into Korean.
> Just translated github-git-cheat-sheet INTO KOREAN

- advanced/index-extras.md
This is related to the build failure described in #393.
> remove include-slides

- _layouts/site.html
This is already included in the bare.html layout file.
> Remove </html> end tag from site.html

- downloads/sk/github-git-cheat-sheet.md
- index.html
This is a Slovak translation of Git Cheat Sheet from Github that you can find on [Github Resources page](https://services.github.com/resources/).
Slovak language is also very similar to Czech what means that now it's accessible to over **15 million Slovak & Czech people**.
I hope that I followed all the rules for contribution correctly and believe that it's ready for merge.
> Slovak Github Git Cheat Sheet

- _includes/intro-video.html
Following up on #412 , I've updated the video to remove the issues steps, as well as the "STEP BLANKS" transitions.
Looking for a quick 👍 or two from @github/services-training on the changes 😄
> Replace video

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This is a rough first 🔪 at creating a consistent issue/PR template that is beginner friendly, related to https://github.com/github/training-kit/issues/415. 
Some Items that I'd still like to work on:
@github/services-training I'd love any contributions that you can think of to make this better! @beardofedu you get a specific ping because you 🎸 documentation.
> Pull Request and Issue Template Updates

- downloads/submodule-vs-subtree-cheat-sheet.md
**tl;dr** There are a lot of resources out there on submodules, subtrees, and pros and cons of each for dependency management. This cheat sheet is an attempt to put the two side by side for a comparison.
Are there other topics we should add? For example, should we add information on:
- the actual implementation of each
- removing??
- dealing with a submodule after a change on a branch
- splitting commits between subtrees and the container repo
/cc @hectorsector @brianamarie @beardofedu @hollenberry @jordanmccullough @brntbeer for :eyes: and 💭
> Submodule vs Subtree Cheat sheet

- _includes/activity/github-CLI/clisurvey.md
- _includes/activity/github-desktop/desktopsurvey.md
- paths/git-trouble/fc-scenarios.md
- paths/github-cli/16-merge-changes.md
- paths/github-desktop/16-merge.md
- paths/intro-to-github/13-celebrate.md
Hey @github/services-training ! Added links to the new surveys and changed the wording a bit for transparency before click. 
It looks good on my end locally, but I'd ❤️  to 🚢  with two Approvals 😄
> Update link for intro survey - add feedback to new courses

- _includes/tell-me-why/create-issue.md
- _includes/tell-me-why/manage-notifications.md
- paths/intro-to-github/02-join-class-repo.md
**TL;DR**
* This file can be inserted somewhere to return instructions to _manage notifications_.
Instructions to silence notifications became redundant after the access method changed.  
Closes #468 
* What is a good location to insert these instructions?
* Include it in one of the course _Tell Me Why_ sections
Suggestions welcome @beardofedu 
---
newbie alert: @r5atom's first pull request with his account age being <24h
> Create description of managing notifications

- downloads/github-bash-cheat-sheet.md
This is just kind of a draft. I can add more material or make comments more descriptive once it's been placed inside a PDF. This is for #399
> so github users can become more familiar with bash

- _includes/help-build-fail.md
**TL;DR**
Expansion of troubleshoot hints how to deal with 404 errors as described in #480.
Feedback and edits welcome.
Locally build the website and check if it renders correctly. The file is currently included on page 10 of the 102 class.
> 404 troubleshoot hints

- _includes/intro-video.html
**TL;DR**
This PR updates our Lightning Video to reflect the most recent issue changes to our curriculum, as noted by a few recent community members. 
closes #479 
@github/services-training or @jameshenrylittle I'd love a review to make sure I didn't break anything unexpected. 😄 
Following a merge, I'll deprecate the old video and change permissions on YouTube.
> Update lightning video with issue changes

- paths/git-trouble/fc-scenarios.md
**TL;DR**
closes #484 
Hey @beardofedu! I'd love to 🚢  this one following your review. Builds locally on my machine. 
- Do you want to break those issue comments into new issues or should I tackle that?
> Fix Broken Links in Git Trouble

- paths/intro-to-github/00-welcome.md
- self-study.md
**TL;DR**
resolves #477 
- @crichID / @brianamarie I tried to look for the Patchwork content that @beardofedu had created, but this looks like its been absorbed. Is that hiding somewhere for us to add to this PR? 
If not, happy to ship with one! This builds fine on my machine.
> Adds "What is GitHub" video to On Demand

- paths/windows/01-getting-started.md
- paths/windows/01a-installing-git.md
- paths/windows/01b-configure-git.md
- paths/windows/01d-git-credentials.md
The headings in the course didn't match the side nav so I am creating and closing this PR to fix those issues. ❤️
> Windows for Users - Clean Up Headings

- paths/windows/03-visual-source-int.md
> title didnt match side nav

- paths/intro-to-github/03-exploring-repository.md
**TL;DR**
The UI was modified but our course content didn't. This PR resolves that. This issue was brought up in an e-mail to us, so no Issue to link, but shout out to `insert GitHub handle`.
Can someone review this and make sure it makes sense?
Do we need to modify the video linked on this page due to the UI changes? 
Whoever has time to throw some 👀 on this, it would be helpful ❤️
> Update content based on UI changes

- _includes/activity/intro-to-github/00-create-github-account.md
Nothing more than a minor typo correction.
> Minor typo correction

- _includes/timeline.html
**TL;DR**
I didn't notice that the layout duplicated sides when reviewing this: #510 , so here is a fix for that.  
- @crichID since you created #510 
- @hectorsector since you helped review #510
> Rearrange Timeline Layout

- paths/electron/starting-with-electron/outline.md
**TL;DR**
This is the outline for Electron: Building an App From Scratch 
_Note: This will be merged into the `electron-course` branch, the dev branch for the public ship of the electron course._
@github/services-training @lee-dohm: 
- Are these the right topics? 
- What questions should we be answering with this unit? 
- What should the breakdown of topics look like? 
- Get review and 👍 on topics and breakdown of topics 
@github/services-training and @lee-dohm for review, comments, and tweaks on specific questions above. Please feel free to mention or bring in anyone else who may have good feedback here.
> Outline for getting started with electron

- paths/electron/distributing/outline.md
Just as the other pull requests #533 and #531, this is an outline for the third unit: Sharing and Distributing Electron Apps.
It touches on what to do after you have a compiled app, where and how to share it for different operating systems, how to set up downloads from a website, and what legal things need to be considered before sharing. 
cc @github/services-training and @lee-dohm for review and edits 🎉
> Draft outline for sharing and distributing electron apps

- _includes/masthead.html
Add links to pages that will exist in the new services site.
> 🔗 Add links to new services pages

- _data/navigation.yml
- _includes/electron.html
- _includes/timeline.html
- paths/electron/starting-with-electron/01-getting-started.md
- paths/electron/starting-with-electron/02-electron-boilerplate.md
- paths/electron/starting-with-electron/03-git-repository.md
- paths/electron/starting-with-electron/04-creating-app-files.md
- paths/electron/starting-with-electron/05-running-the-app.md
- paths/electron/starting-with-electron/06-add-to-index.md
- paths/electron/starting-with-electron/07-add-to-css.md
- paths/electron/starting-with-electron/08-add-to-js.md
- paths/electron/starting-with-electron/09-celebrate.md
- paths/electron/starting-with-electron/outline.md
**TL;DR**
This pull request adds the copy for the "Getting Started" with Electron course, and will be merged into `electron-course`. 
Originally, this had a goal ship date of Friday, July 28th. I'm not sure if that's still a realistic date, but any help is appreciated.  cc @github/services-training for direct commits, feedback on flow, and any general review or comments. 😊 
Context: 
- [Main tracking issue](https://github.com/github/services-training/issues/493) (<-In private repository, so all may not be able to see)
- [Project board](https://github.com/github/training-kit/projects/2)
We'll know this PR is done when there's words and base descriptions on each page. It doesn't have to be draft or final review ready, but enough for us to get through the course with directions.
> Electron getting started draft

- _includes/help-build-fail.md
- _layouts/simple-class.html
- paths/intro-to-github/11-merging-pull-requests.md
**TL;DR**
This pull request makes the **Introduction to GitHub** on-demand course more accessible to screen readers. https://github.com/github/training-kit/issues/532
- Does this do enough? 
- What am I missing?
- Does it actually work? 
@github/services-training & @JasonEtco for 👀 and review
> Add alt text intro course

- paths/electron/starting-with-electron/02-electron-boilerplate.md
- paths/electron/starting-with-electron/04-creating-app-files.md
- paths/electron/starting-with-electron/05-running-the-app.md
- paths/electron/starting-with-electron/06-add-to-index.md
- paths/electron/starting-with-electron/07-add-to-css.md
- paths/electron/starting-with-electron/08-add-to-js.md
Overall I think this is a good course. 👍 
This PR suggests a few minor changes that are more in keeping with idiomatic npm and Electron style.
> add minor changes to electron course

- _includes/activity/github-CLI/clisurvey.md
- _includes/activity/github-desktop/15-collaborate-prs.md
- _includes/activity/github-desktop/desktopsurvey.md
- _includes/tell-me-why/two-stage-commit.md
- paths/github-cli/14-review-local-workflow.md
- paths/github-desktop/01-class-introduction.md
This relates to Emoji Accessibility. https://github.com/github/training-kit/issues/532
Since this is a small change, I will 🚢 with 1 👍 from @github/services-training
> Fix up some images and emojis in GitHub Desktop course

- _includes/tell-me-why/trouble-rebase.md
- _includes/tell-me-why/trouble-reset-xref.md
- _includes/tell-me-why/trouble-reset.md
- paths/git-trouble/fc-accidentcommit.md
- paths/git-trouble/fc-commitbroke.md
- paths/git-trouble/fc-commitsucks.md
- paths/git-trouble/fc-manycommits.md
- paths/git-trouble/fc-scenarios.md
- paths/git-trouble/fc-setup.md
- paths/git-trouble/fc-wrongbranch.md
… trouble course
**TL;DR**
Git Outta Trouble: Make sure all images and links work and are accessible
Related to https://github.com/github/training-kit/issues/532
I will 🚢 with 1 👍 from @github/services-training
> Git Outta Trouble: Make sure all images and links work and are accessible

- downloads/id/github-git-advanced-cheat-sheet.md
- downloads/id/github-git-cheat-sheet.md
This update for fixing the false translation and have done review and patching by  @chocochino for aswering this #401 and #402
> Indonesian Translation

- paths/electron/packaging-apps/03-adding-an-icon.md
- paths/electron/starting-with-electron/03-git-repository.md
- paths/electron/starting-with-electron/08-add-to-js.md
- paths/graphql/01-introduction.md
- paths/graphql/02-first-use.md
- paths/graphql/03-first-query.md
- paths/graphql/04-query-info.md
- paths/graphql/05-another-query.md
- paths/graphql/06-mutation.md
**TL;DR**
This pull request makes some small changes to the Electron course and the GraphQL course in an effort to make the courses more accessible to screen readers. 
- Relates to https://github.com/github/training-kit/issues/532.
@github/services-training I will 🚢 with 1 👍
> Electron & GraphQL accessible emoji fix

- downloads/fr/github-git-cheat-sheet.md
A tiny update for fixing broken markdown on French translation. Looks funny, huh?
> Fix markdown on French translation

- _includes/masthead.html
- resources/index.html
Add slashes to various URLs within On-Demand to avoid redirects from no slash to yes slash.
> Add slashes to URLs, prevents redirects

- resources/cheatsheets/index.html
Fix typo introduced in https://github.com/github/training-kit/pull/560
> Fix typo :abcd:

- _includes/activity/intro-to-github/00-create-github-account.md
- _includes/activity/intro-to-github/01-join-intro-repo.md
- _includes/activity/intro-to-github/03-create-branch.md
- _includes/activity/intro-to-github/04-create-a-file-on-github.md
- _includes/activity/intro-to-github/05-create-a-pull-request.md
- _includes/activity/intro-to-github/05a-collaborate-on-pull-request.md
- _includes/activity/intro-to-github/06-merge-a-pr.md
- _includes/help-build-fail.md
- _includes/help-gh101-common.md
- _includes/help-gh102-103-404.md
- _includes/tell-me-why/manage-notifications.md
- paths/github-cli/16-collaborate.md
- paths/github-desktop/16-collaborate.md
- paths/intro-to-github/00-welcome.md
- paths/intro-to-github/01-create-github-account.md
- paths/intro-to-github/02-join-class-repo.md
- paths/intro-to-github/03-exploring-repository.md
- paths/intro-to-github/04-github-flow.md
- paths/intro-to-github/05-creating-a-branch.md
- paths/intro-to-github/06-find-coordinates.md
- paths/intro-to-github/07-working-on-github.md
- paths/intro-to-github/08-create-pull-request.md
- paths/intro-to-github/09-collaborate-pull-request.md
- paths/intro-to-github/10-edit-on-github.md
- paths/intro-to-github/11-merging-pull-requests.md
- paths/intro-to-github/12-celebrate.md
**TL;DR**
This pull request makes a number of small changes to GitHub 101 including but not limited to:
- Standardizing bolding
- Updating content based on UI changes
- Fix an issue where an image wasn't loading
- I added a period at the end of a numbered step, it was glorious
Closes #568 
Currently not ready for 👀 , at mentions to come. ❤️
> Update GitHub 101

- _includes/activity/github-desktop/01-create-repository.md
- _includes/activity/github-desktop/12-add-class-repo.md
- _includes/activity/github-desktop/16-merge-pr.md
- _includes/activity/github-desktop/choose-a-theme.md
- _includes/refresh/github-CLI/create-pr.md
- _includes/refresh/github-CLI/local-review.md
- _includes/refresh/github-CLI/pull-request.md
- _includes/tell-me-why/create-remote.md
- _includes/tell-me-why/git-configuration.md
- _includes/tell-me-why/github-pages.md
- _includes/tell-me-why/local-remote.md
- _includes/tell-me-why/two-stage-commit.md
- paths/github-cli/02-local-configurations.md
- paths/github-cli/05-cloning.md
- paths/github-cli/06-create-branch.md
- paths/github-cli/07-local-files.md
- paths/github-cli/08-2-step-commit.md
- paths/github-cli/09-push-and-pull.md
- paths/github-cli/11-view-your-site.md
- paths/github-cli/12-sync-local-repo.md
- paths/github-cli/13-join-class-repo.md
- paths/github-cli/14-review-local-workflow.md
- paths/github-cli/15-push-and-open-pr.md
This PR is a full review of GH 103. It mostly employs our new [style guidelines](https://github.com/github/training-kit/blob/15286e494d46cf78f1555602ba1a4931b2a05f7d/CONTRIBUTING.md#writing-new-content) introduced in #571, but also makes some necessary corrections and clarifications.
> GitHub 103 review

- paths/intro-to-github-es/11-merge-pull-requests.md
**TL;DR**
Fix some broken links on the Spanish version.
`closes` issue #592
> Fix broken links

- paths/merge-conflict/00-intro.md
Adding disclaimer to the Merge Conflict course.
> Add copyright stuff

- paths/merge-conflict/00-intro.md
@crichID I broke the merge-conflict index.html file by incorrectly adding the content without the proper spacing. This resolves that issue. That I made.
> add space so file works

- README.md
Tried to make a couple of sentences parse a little better. Nothing more than a bit of plain Englishing.
> Minor rewording

- paths/git-trouble/fc-scenarios.md
- paths/git-trouble/fc-setup.md
- paths/git-trouble/fc-welcome.md
**TL;DR**
Did a bit more Plain English and Grammarly.com checking of some of the "Help! It's all gone horribly wrong" sections.
> A few more Plain English changes

- paths/git-trouble/fc-scenarios.md
This is what happens when you forget to test locally 😦
> More yaml indenting

- assets/js/script.js
This PR closes #594 by wrapping all GIFs with an anchor tag that opens in a new window.
> Open GIFs in a new window

- resources/cheatsheets/index.html
This is a truly small typo fix.
> Small typo repaired.

- _data/navigation.yml
- paths/merge-conflict/00-intro.md
- paths/merge-conflict/01-normal-merge.md
- paths/merge-conflict/02-mc-desc.md
- paths/merge-conflict/02-setup-repository.md
- paths/merge-conflict/02-your-first-conflict.md
- paths/merge-conflict/04-ex-01.md
- paths/merge-conflict/05-ex-02.md
- paths/merge-conflict/06-ex-03.md
- paths/merge-conflict/07-ide-intro.md
- paths/merge-conflict/08-ide-atom.md
- paths/merge-conflict/09-ide-vs-ext.md
- paths/merge-conflict/10-ide-eclipse.md
- paths/merge-conflict/11-ide-vs-code.md
- paths/merge-conflict/12-ide-gh-desktop.md
- paths/merge-conflict/13-what-next.md
Added the "help" button to the Merge Conflict Course.
> Merge Conflict - Help button

- _includes/activity/github-desktop/desktopsurvey.md
**TL;DR**
Change from http to https
> Update http to https link desktopsurvey.md

- paths/git-trouble/fc-scenarios.md
> Edit http link in fc-scenarios.md

- downloads/it/github-git-cheat-sheet.md
alternatively, you can say more precisely
`Carica tutti i cambiamenti effettuati nel branch locale su GitHub`
at line `239`
**TL;DR**
> A better Italian form

- _includes/seo.html
**TL;DR**
<Have added Meta Tag for Description >
Issue #680
> Updated SEO to include Meta Description

- README.md
**TL;DR**
The noun phrase content seems to be missing a determiner before it. Consider adding an article
No questions
None
Let me know if you appreciate this want me to work something like this more
> Updated the README.MD

- README.md
> add a comma

- downloads/subversion-migration.md
> Fix typo tim->time

- CONTRIBUTING.md
Fixing issue invalid link to index.html in CONTRIBUTING.md
closes #675
> Fix link in CONTRIBUTING.md issue #675

- _includes/breadcrumbs.html
- _includes/footer.html
- _includes/light-hero.html
- downloads/tr/github-git-cheat-sheet.md
- index.html
Turkish added and some html edited
> Turkish language

- CONTRIBUTING.md
**TL;DR**
@crichID Please review.
> Fixing the typo in the readme file

- README.md
> Fixed a little bit of grammar

- downloads/az/github-git-cheat-sheet.md
- index.html
- Azerbaijani translation completed
- Link to index.html added
@GasimGasimzada, please check if there are any translation or grammatical errors.
> add Azerbaijani localization

- downloads/github-bash-cheat-sheet.md
- downloads/github-git-cheat-sheet.md
**TL;DR**
Updated the Git cheatsheet where the git init method was explained. I added the fact that after creating the local repository, we have to link it with the remote repository using some link name like origin.
@brianamarie Please review 🙂
> Update github-git and github-bash cheatsheets

- git-guides/git-add.md
- git-guides/git-clone.md
- git-guides/git-commit.md
- git-guides/git-init.md
- git-guides/git-overview.md
- git-guides/git-pull.md
- git-guides/git-push.md
- git-guides/git-status.md
- git-guides/install-git.md
This pull request removes some outdated comments for the `/git-guides` directory. It doesn't affect any auto-deployed code.
Thank you @tobiasahlin for pointing out these comments. 🙏
> Remove outdated comments

- git-guides/git-overview.md
Add links to other articles from the git overview page. Also removed some old comments 🙏 
cc @brianamarie
> Add internal links from overview

- git-guides/install-git.md
**TL;DR**
Fixed a minor typo.
Thank you
> Fixed a minor typo

- downloads/subversion-migration.md
Fixed some minor typos that were found.
> Fixed some minor typos

- .github/ISSUE_TEMPLATE.md
I fix a broken link in **ISSUE TEMPLATE**.
> Fix broken link in ISSUE TEMPLATE

- index.html
Fixed typo: Changed 'Available in a multiple languages.' to 'Available in multiple languages.'
**TL;DR**
> Typo fix in index.html

- downloads/de/github-git-cheat-sheet.md
**TL;DR**
I fixed some grammar errors and also explained more precisely some concepts.
> Improve german git cheat sheet

- downloads/github-git-cheat-sheet.md
> Define git init

- downloads/sk/github-git-cheat-sheet.md
**TL;DR**
This is a bunch of minor fixes and wording adjustments to Slovak translation of the cheatsheet. 
Pinging @marekdlugos (as the main contributor of this translation) for any comments.
N/A
Ready for review.
> Minor tweaks to SK cheatsheet translation

- downloads/es_ES/submodule-vs-subtree-cheat-sheet.md
- index.html
**TL;DR**
Translates Submodules vs. Subtrees to Spanish.
ready for :eyes: 
Spanish reviewers:
@CesarAscencioV @alxalmora
> Translates Submodules vs. Subtrees to Spanish

- downloads/github-git-cheat-sheet.md
Updated definition of git log --follow
**TL;DR**
The definition of `git log --follow` in the github git-cheat-sheet.md was different than the actual meaning. This pull request updates that definition.
closes #759
> Updated github-git-cheat-sheet.md

- git-guides/git-init.md
**TL;DR**
Change master with main in the training manual as with the [change](https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/)
> change master to main for new repositories

- git-guides/git-overview.md
Hi @SEOGoddess and @brianamarie, this the PR to address this [thread](https://github.slack.com/archives/CU34FQT7D/p1612906028003500). 
I really did not do much apart from adding the little that was missing, putting some keywords here and there and restructuring the page so it flows a little better. I feel like most of the content that was already there covers the questions but please let me know if you'd prefer that I use the exact questions from the list or if something else is required! :)
> Add FAQ questions

- downloads/zh_CN/github-git-cheat-sheet.md
git pull and push were put in the wrong place
**TL;DR**
> Switched "git push" and "git pull"

- downloads/tr/github-git-cheat-sheet.md
Improve Turkish github-git-cheat-sheet.
> Fix typo and add new translation

- git-guides/git-init.md
**TL;DR**
Step 4 already tells you to make at least one commit before pushing:
> Shape your history into at least one commit by using `git add` to stage the existing files, and `git commit` to make the snapshot.`
> Remove 'make at least one commit' from Step 1

- downloads/zh_TW/github-git-cheat-sheet.md
Improve translation based on the reviews from @ralphchung in #932.
No question.
Wait for reviewers' opinions to decide the next steps. 
Hi @parkerbxyz @ralphchung, I have tried to improve the translation suggested in #932, feel free to review it, thank you 👍
> Improve translation based on review
